# **Ex.1 - Answer**

**1.1 - Inizialization**

In [48]:
import numpy as np

n = 4

A = np.random.random((n, n))
B = np.random.random((n, n))
print("A: ") 
print(A)
print("B: ")
print(B)

A: 
[[0.86258129 0.34638484 0.67921902 0.95538783]
 [0.28191607 0.69457324 0.27316756 0.44990048]
 [0.11991009 0.93632608 0.09698951 0.64617571]
 [0.88641021 0.78569185 0.37138496 0.23656411]]
B: 
[[0.48030038 0.37644069 0.86050308 0.15378353]
 [0.89346484 0.01365184 0.38884896 0.7065443 ]
 [0.96385783 0.92020708 0.4947985  0.85926812]
 [0.08160096 0.76505941 0.25835846 0.73050624]]


**1.2 - ijk Cycle** <br/>
*This Cylce computes in the first iteration of k indices the dot product of the i row of A with the j column of B. Then it proceeds with computing the same for the row i, changing the value of the column j. Finally, iterating i, it does the same on the remaining rows*

In [23]:
C = np.zeros((n,n))
def ijk(A,B,C):
  for i in range(0,n):
    for j in range(0,n):
      for k in range(0,n):
        C[i,j] = A[i,k]*B[k,j] + C[i,j] 
  return C

C = ijk(A,B,C)
print(C)
if ((C-np.dot(A,B)).all()<10**-6):
  print("CHECK: TRUE")
else:
  print("CHECK: FALSE")

[[0.73261853 1.28475397 1.3050136  1.11962173]
 [0.90920846 1.78410192 1.27589354 1.5705296 ]
 [0.84108691 1.60656643 1.30316083 1.57542787]
 [1.0163505  2.0886296  1.26045222 1.86579849]]
CHECK: TRUE


**1.2 - ijk Cycle (Optimized)**

In [24]:
C = np.zeros((n,n))
def ijk(A,B,C):
  for i in range(0,n):
    for j in range(0,n):
      C[i,j] = np.dot(A[i,:],B[:,j]) + C[i,j] 
  return C

C = ijk(A,B,C)
print(C)
if ((C-np.dot(A,B)).all()<10**-6):
  print("CHECK: TRUE")
else:
  print("CHECK: FALSE")

[[0.73261853 1.28475397 1.3050136  1.11962173]
 [0.90920846 1.78410192 1.27589354 1.5705296 ]
 [0.84108691 1.60656643 1.30316083 1.57542787]
 [1.0163505  2.0886296  1.26045222 1.86579849]]
CHECK: TRUE


**1.3 - jik Cycle** <br/>
*This cycle, similarly to the previous, computes the dot product of the i row of A and the j column of B. Then it proceeds iterating i, meaning computing the same k cycle for the first column of C. Finally, in the j iterations, it does the same on the following columns of C*

In [34]:
C = np.zeros((n,n))
def jik(A,B,C):
  for j in range(0,n):
    for i in range(0,n):
      for k in range(0,n):
        C[i,j] = A[i,k]*B[k,j] + C[i,j] 
  return C

C = jik(A,B,C)
print(C)
if ((C-np.dot(A,B)).all()<10**-6):
  print("CHECK: TRUE")
else:
  print("CHECK: FALSE")

[[0.73261853 1.28475397 1.3050136  1.11962173]
 [0.90920846 1.78410192 1.27589354 1.5705296 ]
 [0.84108691 1.60656643 1.30316083 1.57542787]
 [1.0163505  2.0886296  1.26045222 1.86579849]]
CHECK: TRUE


**1.3 - jik Cycle (Optimized)**

In [33]:
C = np.zeros((n,n))
def jik(A,B,C):
  for j in range(0,n):
    for i in range(0,n):
      C[i,j] = np.dot(A[i,:],B[:,j]) + C[i,j] 
  return C

C = jik(A,B,C)
print(C)
if ((C-np.dot(A,B)).all()<10**-6):
  print("CHECK: TRUE")
else:
  print("CHECK: FALSE")

[[0.73261853 1.28475397 1.3050136  1.11962173]
 [0.90920846 1.78410192 1.27589354 1.5705296 ]
 [0.84108691 1.60656643 1.30316083 1.57542787]
 [1.0163505  2.0886296  1.26045222 1.86579849]]
CHECK: TRUE


**1.4 - ikj Cycle** <br/>
*The first iterations of j compute the product between the i,k value of A and the row k of B, computing the first term of the dot product between the k column of A and the k column of B. It then proceeds iterating k, computing the following terms of the dot product. Finally it does the same for all rows i.*

In [32]:
C = np.zeros((n,n))
def ikj(A,B,C):
  for i in range(0,n):
    for k in range(0,n):
      for j in range(0,n):
        C[i,j] = A[i,k]*B[k,j] + C[i,j] 
  return C

C = ikj(A,B,C)
print(C)
if ((C-np.dot(A,B)).all()<10**-6):
  print("CHECK: TRUE")
else:
  print("CHECK: FALSE")

[[0.73261853 1.28475397 1.3050136  1.11962173]
 [0.90920846 1.78410192 1.27589354 1.5705296 ]
 [0.84108691 1.60656643 1.30316083 1.57542787]
 [1.0163505  2.0886296  1.26045222 1.86579849]]
CHECK: TRUE


**1.4 - ikj Cycle (Optimized)**

In [31]:
C = np.zeros((n,n))
def ikj(A,B,C):
  for i in range(0,n):
    for k in range(0,n):
      aux = A[i,k]
      for j in range(0,n):
        C[i,j] = aux*B[k,j] + C[i,j] 
  return C

C = ikj(A,B,C)
print(C)
if ((C-np.dot(A,B)).all()<10**-6):
  print("CHECK: TRUE")
else:
  print("CHECK: FALSE")

[[0.73261853 1.28475397 1.3050136  1.11962173]
 [0.90920846 1.78410192 1.27589354 1.5705296 ]
 [0.84108691 1.60656643 1.30316083 1.57542787]
 [1.0163505  2.0886296  1.26045222 1.86579849]]
CHECK: TRUE


**1.5 - jki Cycle** <br/>

In [30]:
C = np.zeros((n,n))
def jki(A,B,C):
  for j in range(0,n):
    for k in range(0,n):
      for i in range(0,n):
        C[i,j] = A[i,k]*B[k,j] + C[i,j] 
  return C

C = jki(A,B,C)
print(C)
if ((C-np.dot(A,B)).all()<10**-6):
  print("CHECK: TRUE")
else:
  print("CHECK: FALSE")

[[0.73261853 1.28475397 1.3050136  1.11962173]
 [0.90920846 1.78410192 1.27589354 1.5705296 ]
 [0.84108691 1.60656643 1.30316083 1.57542787]
 [1.0163505  2.0886296  1.26045222 1.86579849]]
CHECK: TRUE


**1.5 - jki Cycle (Optimized)**

In [29]:
C = np.zeros((n,n))
def jki(A,B,C):
  for j in range(0,n):
    for k in range(0,n):
      aux=B[k,j]
      for i in range(0,n):
        C[i,j] = A[i,k]*aux + C[i,j] 
  return C

C = jki(A,B,C)
print(C)
if ((C-np.dot(A,B)).all()<10**-6):
  print("CHECK: TRUE")
else:
  print("CHECK: FALSE")

[[0.73261853 1.28475397 1.3050136  1.11962173]
 [0.90920846 1.78410192 1.27589354 1.5705296 ]
 [0.84108691 1.60656643 1.30316083 1.57542787]
 [1.0163505  2.0886296  1.26045222 1.86579849]]
CHECK: TRUE


**1.6 - kij Cycle** <br/>
*The iteration of j computes all the first terms of the dot product for C(i,j) on the row i. The iteration of i does the same for the following rows. Finally, iterating k, adds all the other terms of the dot products in all the postions i,j of C*

In [35]:
C = np.zeros((n,n))
def kij(A,B,C):
  for k in range(0,n):
    for i in range(0,n):
      for j in range(0,n):
        C[i,j] = A[i,k]*B[k,j] + C[i,j] 
  return C

C = kij(A,B,C)
print(C)
if ((C-np.dot(A,B)).all()<10**-6):
  print("CHECK: TRUE")
else:
  print("CHECK: FALSE")

[[0.73261853 1.28475397 1.3050136  1.11962173]
 [0.90920846 1.78410192 1.27589354 1.5705296 ]
 [0.84108691 1.60656643 1.30316083 1.57542787]
 [1.0163505  2.0886296  1.26045222 1.86579849]]
CHECK: TRUE


**1.6 - kij Cycle (Optimized)**

In [37]:
C = np.zeros((n,n))                                                             #Rec: Given two vectors, a = [a0, a1, ..., aM] and b = [b0, b1, ..., bN], the outer product is the matrix
def kij(A,B,C):                                                                 #
  for k in range(0,n):                                                          #[[a0*b0  a0*b1 ... a0*bN ]
    C = np.outer(A[:,k],B[k,:]) + C                                             #[a1*b0    .
  return C                                                                      #[ ...          .
                                                                                #[aM*b0            aM*bN ]]
C = kij(A,B,C)
print(C)
if ((C-np.dot(A,B)).all()<10**-6):
  print("CHECK: TRUE")
else:
  print("CHECK: FALSE")

[[0.73261853 1.28475397 1.3050136  1.11962173]
 [0.90920846 1.78410192 1.27589354 1.5705296 ]
 [0.84108691 1.60656643 1.30316083 1.57542787]
 [1.0163505  2.0886296  1.26045222 1.86579849]]
CHECK: TRUE


**1.7 - kji Cycle**

In [38]:
C = np.zeros((n,n))
def kji(A,B,C):
  for k in range(0,n):
    for j in range(0,n):
      for i in range(0,n):
        C[i,j] = A[i,k]*B[k,j] + C[i,j] 
  return C

C = kji(A,B,C)
print(C)
if ((C-np.dot(A,B)).all()<10**-6):
  print("CHECK: TRUE")
else:
  print("CHECK: FALSE")

[[0.73261853 1.28475397 1.3050136  1.11962173]
 [0.90920846 1.78410192 1.27589354 1.5705296 ]
 [0.84108691 1.60656643 1.30316083 1.57542787]
 [1.0163505  2.0886296  1.26045222 1.86579849]]
CHECK: TRUE


**1.7 - kji Cycle (Optimized)**

In [49]:
C = np.zeros((n,n))
def kji(A,B,C):
  for k in range(0,n):
    C = np.outer(A[:,k],B[k,:]) + C
  return C

C = kji(A,B,C)
print(C)
if ((C-np.dot(A,B)).all()<10**-6):
  print("CHECK: TRUE")
else:
  print("CHECK: FALSE")

[[1.45641193 1.68539009 1.45985432 1.65893505]
 [1.05598816 0.7111782  0.76407222 1.09748009]
 [1.04037995 0.64153485 0.68220765 1.23537143]
 [1.50499736 0.86714367 1.31315323 1.1833722 ]]
CHECK: TRUE


Example of a solution:
www.maia.ub.es/~vieiro/docencia/NLA/



# Ex. 2 - Answer


**2.1 - Inizialization**

In [42]:
import numpy as np

p=7
n=2**p  #dimension (e.g. a power of 2)

A=np.random.rand(n,n); B=np.random.rand(n,n)  #random matrices

C1=np.dot(A,B);  print('Direct computation %d\n' % n);  #direct multiplication of matrices

Direct computation 128



**2.2 - Block Multiplication Function**

In [45]:
def blockmatprod(A,B):
  C = np.zeros((n,n))
  for i in range (0,N): 
        for j in range (0,N): # <- here we load block C[i,j] into fast  memory
            for k in range (0,N): # <- here we load block A[i,k], B[k,j] into fast memory
                for ii in range (i*b,(i+1)*b): 
                    for jj in range (j*b,(j+1)*b):  
                        for kk in range (k*b,(k+1)*b):
                            C[ii,jj]=C[ii,jj]+A[ii,kk]*B[kk,jj];
            # <- here we write block C[ii,jj] into slow memory
  return C

for pp in range (0,p+1):
     N=2**pp; b=int(n/N); 
     C2=blockmatprod(A,B);  #block matrix multiplication
     print(' %4d %4d %4d %24.16e\n'%(n,b,N,np.linalg.norm(C2-C1,np.inf)))

  128  128    1   2.8776980798284058e-13

  128   64    2   2.8776980798284058e-13

  128   32    4   2.8776980798284058e-13

  128   16    8   2.8776980798284058e-13

  128    8   16   2.8776980798284058e-13

  128    4   32   2.8776980798284058e-13

  128    2   64   2.8776980798284058e-13

  128    1  128   2.8776980798284058e-13



# Ex. 3 Answer

**3.1 - Inizialization**

In [ ]:
import numpy as np
import scipy.linalg

n = 4

A = np.random.random((n, n))
B = np.random.random((n, n))
print("A: ") 
print(A)
print("B: ")
print(B)

**Step 1 - LU Factorization**

In [ ]:
def lunopiv(A,n,ptol):
  for k in range(0,n-1):
    pivot = A[k,k]
    if abs(pivot) < ptol:
      print("no pivot encountered")
      break
    for i in range(k+1,n):
      A[i,k] = A[i,k]/pivot
      for j in range(k+1,n):
        A[i,j] = A[i,j] - A[i,k]*A[k,j]
  L = np.eye(n)+np.tril(A,-1)
  U = np.triu(A)
  return L,U

**Step 2**

In [ ]:
A = np.zeros((n,n))
for i in range(0,n):
  for j in range (0,n):
    A[i,j]=np.random.normal(0,10)

LU=np.zeros((n,n))

r=3
nblocks = int(n/r)
Aij=np.zeros((nblocks,nblocks), np.matrix)

S=np.copy(A)

for i in range(0, nblock-1):
  Aij[0,0] = np.copy(S[o:r,0:r]); Aij[0,1] = np.copy(S[0:r, r:n])
  #Seconda riga di blocchi

  print(??????????)
  U12=np.linalg.solve(L11,Aij[0,1])   #Gaussian Elimination with Partial Pivoting
  L21=np.linalg.solve(U11.T,Aij[1,0].T)

  LU[i*r:(i+1)*r, i*r:(i+1)*r]=np.copy(np.tril(L11,-1)+U11)   #Step 3
  LU[i*r:(i+1)*r,(i+1)*r:n]=np.copy(U12)   
  LU[(i+1)*r:n,i*r:(i+1)*r]=np.copy(L21t.T)

  S=Aij[1,1]-np.dot(L21t.T,U12)   #Step 4

Aij[0,0] = S[0:r,0:r]
??
??

??
??

#np.solve == Gaussian Elimination with Partial Pivoting (GEPP)

**Step 3**

In [ ]:
#Per risolvere il sistema come un sistema lineare classico si fanno i trasposti, il trasposto del prodotto è l'inverso prodotto dei trasposti, e si ottiene il sistema classico


**Step 4**